name: parking
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.2

dependencies:
  auth: ^8.1.0
  bloc: ^8.1.0
  carousel_slider: ^4.1.1
  cloud_firestore: ^3.5.1
  cupertino_icons: ^1.0.5
  equatable: ^2.0.5
  firebase_auth: ^3.11.2
  firebase_core: ^1.24.0
  
  firebase_database: ^9.1.7
  firebase_storage: ^10.3.11
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_inset_box_shadow: ^1.0.8
  flutter_localizations:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.6.0
  focused_menu: ^1.0.5
  font_awesome_flutter: ^10.2.1
  
  
  get: ^4.6.5
  google_fonts: ^3.0.1
  google_maps_flutter: ^2.2.2
  
  group_radio_button: ^1.3.0
  http: ^0.13.5
  intl: ^0.17.0
  modal_progress_hud_nsn: ^0.3.0
  provider: ^6.0.5
  shared_preferences: ^2.0.15
  syncfusion_flutter_calendar: ^20.3.61
  url_launcher: ^6.1.7
  uuid: ^3.0.7

dev_dependencies:
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
  - Assets/images/
